#!/usr/bin/env bash
#Bash script that displays:

#   Creates the file /var/run/myscript.pid containing its PID
#   Displays To infinity and beyond indefinitely
#   Displays I hate the kill command when receiving a SIGTERM signal
#   Displays Y U no love me?! when receiving a SIGINT signal
#   Deletes the file /var/run/myscript.pid and terminates 
# itself when receiving a SIGQUIT or SIGTERM signal

touch /var/run/myscript.pid
pgrep -f 100-process_and_pid_file > /var/run/myscript.pid

i=1
function clean_up()
{
    rm /var/run/myscript.pid
    exit
}
while [[ $i -lt 2 ]];
    do
        echo "To infinity and beyond"
        sleep 2

        trap 'echo "I hate the kill command"' SIGTERM

        trap 'echo "Y U no love me?!"' SIGINT

        trap 'clean_up' SIGQUIT SIGTERM



    done
