#!/usr/bin/env bash
#Bash script that displays:

# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds

TMP_FILE="/tmp/my_process"

# Infinite loop
while true;
    do
        # Create TMP file and write into it.
        echo I am alive! > "$TMP_FILE"
        sleep 2
    done
