#!/usr/bin/env bash
#This script prints a string 10 times
str="Best School"
counter=1

while [[ $counter -le 10 ]];
    do
        echo "$str";
        if [[ $counter -eq 9 ]]; then
            echo "Hi";
        fi
        ((counter++))
    done
