#!/usr/bin/env bash
#This script prints a string 10 times
str="Best School"
counter=1

while [[ $counter -le 10 ]];
    do
        if [[ $counter -eq 4 ]]; then
            echo "bad luck";
        
        elif [[ $counter -eq 8 ]]; then
            echo "good luck";
        
        else
            echo "$str"
        fi
        ((counter++))
    done
