#!/usr/bin/env bash
#This script prints a string counter and strings depanding on cases
counter=1

while [[ $counter -le 20 ]];
    do

        case $counter in
            4)
                echo "bad luck from China";
            ;;
            9)
                echo "bad luck from Japan";
            ;;
            17)
                echo "bad luck from Italy";
            ;;
            *)
                echo $counter;
            ;;
        esac

        ((counter++))
    done
