#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes
hour=0
minut=1

while [[ $hour -lt 13 ]];
    do
	echo "Hour: $hour"
        while [[ $minut -lt 60 ]]; 
        do
            echo $minut
            ((minut++))
        done
	minut=1
	((hour++))
    done
