#!/usr/bin/env bash
#Bash script that displays:
#   The content of the current directory
#   In a list format
#   Where only the part of the name after the first dash is displayed

ls | cut -f 2 -d "-"> LIST;

for i in $(cat LIST);
    do
        echo "$i"
    done
