#!/usr/bin/env bash
#Bash script that  Bash script that gives you information about the school file.

file_name="school"

if [[ -e "./$file_name" ]]; then
    echo "school file exists"

    if [[ -f "./$file_name" ]]; then #file is regular
        echo "school is a regular file"
    fi
    if [[ -s "./$file_name" ]]; then #file is not empty
        echo "school file is not empty"
    else                             #file is empty
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
